### ISSUE TITLE
I can build sparse octree,but i can't import or load

### ISSUE THREAD

**Issue by zhw-github** [zju3dv/Vox-Fusion#1]
hi:
Thank you for your excellent work！
But when I compile the code, I have a problem, the problem comes from the sparse_octrees section.
When I run python setup.py install in sparse octree file, I am able to show successful installation. But when I import svo, an error will be reported, the information is as follows:
>>> import torch
>>> import svo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_svo)

Later I read where your code uses svo, your usage method is 
torch.classes.load_library(
     "third_party/sparse_octree/build/lib.linux-x86_64-3.8/svo.cpython-38-x86_64-linux-gnu.so")
But when I run the whole program it prompts:
OSError: /home/zhanghw/work/Vox-Fusion/src/third_party/sparse_octree/build/lib.linux-x86_64-3.8/svo.cpython-38-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
When I checked my build directory, I found no such file.this is my file tree:
├── bdist.linux-x86_64
├── lib.linux-x86_64-3.7
│   └── svo.cpython-37m-x86_64-linux-gnu.so
├── lib.linux-x86_64-cpython-38
│   └── svo.cpython-38-x86_64-linux-gnu.so
├── lib.linux-x86_64-cpython-39
│   └── svo.cpython-39-x86_64-linux-gnu.so
├── temp.linux-x86_64-3.7
│   ├── build.ninja
│   └── src
│       ├── bindings.o
│       └── octree.o
├── temp.linux-x86_64-cpython-38
│   └── src
│       ├── bindings.o
│       └── octree.o
└── temp.linux-x86_64-cpython-39
    └── src
        ├── bindings.o
        └── octree.o

10 directories, 10 files
But if I replace the file with any of the above dynamic link libraries, it still shows the same error.
My computer environment is python3.9,cuda10.1,gpu 2080Ti,pytorch 1.8.1+cu101
Looking forward to your reply！

**Comment by xingruiy** [comment]
Hi,

Thanks for trying out our code.

It might be that we hard-coded the library path into the program and this is causing problems. However if the compilation was successful you should be able to simply replace the file path in the `load_library` function with that to your compiled library (a `.so` file that corresponds to your python version).

Did you put the absolute path in the `load_library` function or a relative path? Please also. double-check if all libraries are compiled successfully.

**Comment by garylidd** [comment]
We have fixed this bug and update the README.  Our method is built with pytorch version >= 1.10, I noticed that you are using an old version of pytroch, there may be some incompatible features.

**Comment by zhw-github** [comment]
Thanks for your answers, after changing the path, torch.classes.load_library can be imported normally, and I replaced my torch version with 1.10.0.
But when I build sparse_octree and sparse_voxel, I must copy the header file of inlude to the src directory to compile normally, otherwise it will prompt that the header file cannot be found. I changed the path of setup.py as follows:
setup(
    name='svo',
    ext_modules=[
        CppExtension(
            name='svo',
            sources=_ext_sources,
            include_dirs=["./include"],
            extra_compile_args={
                "cxx": ["-O2", "-I./include"]
            },
        )
    ],
    cmdclass={
        'build_ext': BuildExtension
    }
)
When I put the source and include files together, no problem occurs.This may be caused by my compiler environment, if your computer can compile normally, you can ignore this problem

**Comment by garylidd** [comment]
We did notice that the header file not found problem occurs in some environments, the reason is not clear. A workaround solution is to use the absolute path of  include_dirs in setup.py.
