### ISSUE TITLE
Questions about the num_beddings parameter and others

### ISSUE THREAD

**Issue by zhw-github** [zju3dv/Vox-Fusion#13]
Hi,
Sorry to bother you again? I am very interested in your excellent work, so I carefully read some of your code and ask some questions.
1. In Mapping.py,there is such a line of code when initializing the embedded feature vector:
self.embeddings = torch.zeros((num_embeddings, self.embed_dim),....)
you set num_embeddings to 20000, what is the basis for the setting? My understanding is that the setting of embedding should be related to the voxels containing the surface in the space, because you are using sparse voxels with octrees. If this value is set too high, it will not be used. If it is too small, some voxels containing surfaces will not be allocated to the feature vector.          
2. In render_helpers.py,R = pose[: 3, : 3].transpose(-1, -2) # (3,3),why change y,z?

**Comment by garylidd** [comment]
Hi, 
1. You are right, the current setting of num_embeddings is just for experiment, this part can easily be modified to an adaptive allocation strategy.
2. The arguments to torch.transpose refer to dimensions, not specific values.

**Comment by zhw-github** [comment]
> 
Thanks for answering I understand

**Comment by JunyuanDeng** [comment]
> Hi,
> 
> 1. You are right, the current setting of num_embeddings is just for experiment, this part can easily be modified to an adaptive allocation strategy.
> 2. The arguments to torch.transpose refer to dimensions, not specific values.

I assume that it does a  `pose[: 3, : 3].T` operation. I guess it's because of the outputs from `se3pose.py`, which outputs the poses from world coordinate to camera coordinate rather than camera to world.
