### ISSUE TITLE
Weird behavior of svo sampling on mapping thread?

### ISSUE THREAD

**Issue by gwangtaepark** [zju3dv/Vox-Fusion#15]
Hello, 
I just tracked the number of samples per ray and it seems that number of sampling grows as the frame proceeds.
For the tracking, the number seems to be consistent, but for the mapping thread the sample number grows continuously.
For instance, if I run slam from frame 0 to 800, the sample number per ray grows from 20 to 75. 
Is it intended or a wrong behavior?

**Comment by garylidd** [comment]
Thanks for pointing it out, I didn't notice it before. What data are you using? I'll check it out.

**Comment by gwangtaepark** [comment]
Just misunderstood the behavior of the code.
I thought that during mapping 1024 rays per training iteration is used.
(As written in configs/replica/replica.yaml)
But it seems that total rays for each training step is N_rays_each * window_size
So it was number of rays growing, not number of samples. (sample per ray stays almost same)

**Comment by gwangtaepark** [comment]
Even though, on replica/room_0 dataset, the sample per ray increaes.
For the first 300 frames, average number of samples is about 12~13, but in frame 1000 the number of samples is 20.

**Comment by garylidd** [comment]
Hi, 

The number of sampling points depends on the number of intersecting voxels. As the scene expands and voxel blocks increase, the number of samples also increases. You can control the maximum sampling distance with the max_depth parameter in the configuration.
