### ISSUE TITLE
I have a question about coordinate system?

### ISSUE THREAD

**Issue by zhw-github** [zju3dv/Vox-Fusion#16]
Hi,
I'm not too clear about the relationship between the world coordinate system and the voxel coordinate system.
For each output offset t, you add 10 to prevent the coordinates from being less than 0.
Does the voxel coordinate system coincide with the coordinate system after offset?
x from back to front，y from left to right, z from bottom  to  top.
Where is this voxel coordinate system located in the whole volum, it is located at the vertex of the lowermost corner of the left rear.

**Comment by garylidd** [comment]
Hi,

Voxel coordinates are the actual coordinates divided by the voxel size, and the coordinate system is according to general 3D vision tasks, x from left to right, y from top to bottom, z from front to back for each camera frame. 

The leaf node voxels are defined at the corners with minimum coordinates.
