### ISSUE TITLE
I have a question about ray_intersect?

### ISSUE THREAD

**Issue by yanzw1** [zju3dv/Vox-Fusion#17]
Hi,
Very nice work!But i have a question about voxel_heplers.py. In ray_intersect function, what's the mean of the min_depth and max_depth?
I think it should be the index of each ray hitting the voxel, as well as the minimum depth and maximum depth. The minimum depth minus the maximum depth should be equal to voxel_size, but it is not the case? So what are their meanings?

**Comment by garylidd** [comment]
Hi, 
The "min_depth" and "max_depth" are the two depths where the ray intersects each voxel. Since the rays are not parallel to the voxel axis, the distance between them is not necessarily equal to the "voxel_size".
