### ISSUE TITLE
ARKit dataset

### ISSUE THREAD

**Issue by pablovela5620** [zju3dv/Vox-Fusion#2]
Hi, thanks for open sourcing this. 

What software are you using to generate the required ARKit poses/depth? I noticed that ioslogger used [here](https://github.com/zju3dv/NeuralRecon/blob/master/DEMO.md), is this whats also used? I would guess not considering depth maps are required, would something like https://3dscannerapp.com/ work?

**Comment by garylidd** [comment]
We use the RGBD recording software developed internally not ioslogger. I'm not very familiar with 3d scanner app, it looks like a traditional reconstruction like a COLMAP.  If so, it does work without depth, but with the same limitations as traditional SfM + MVS pipelines.

**Comment by pablovela5620** [comment]
> We use the RGBD recording software developed internally not ioslogger. I'm not very familiar with 3d scanner app, it looks like a traditional reconstruction like a COLMAP. If so, it does work without depth, but with the same limitations as traditional SfM + MVS pipelines.

Any plans to make the internal app opensource?

**Comment by xingruiy** [comment]
@pablovela5620  I am afraid that the app we used to capture ARKit scenes has been developed and used within SenseTime and is not publicly available due to company regulations. From my experience 3D scanner app can also be used to obtain rgb/depth/pose, you need to write your own dataloader.
