### ISSUE TITLE
Doubts about the voxel-based sampling

### ISSUE THREAD

**Issue by Riser6** [zju3dv/Vox-Fusion#20]
Thanks for this great work!
But I still have some doubts after reading the paper. When performing ray-voxel intersection test, whether the voxel corresponding to the non-leaf node will be checked to see if it has been hit. In other words，I wonder if there is voxel embeddings attached to the voxel  corresponding to the non-leaf node.
I will be very grateful if you can clear my doubts！

**Comment by garylidd** [comment]
Hi, 

We do not assign embeddings to non-leaf nodes, the purpose of the octree structure is to speed up the indexing of leaf nodes and the ray-voxel intersection test only performs on leaf nodes.

**Comment by Riser6** [comment]
I got it. Thanks again for this great work and your generous sharing!
