### ISSUE TITLE
Code getting stuck near end

### ISSUE THREAD

**Issue by eriksandstroem** [zju3dv/Vox-Fusion#23]
First of all, thanks for providing the code for your project! I was successfully able to install and run your code, but am facing an issue. When running on room 0, it gets stuck after 1894 frames. On office 0 it happens after 1896 frames. I have tried this with repetitive runs and it happens every time.

I am running on Titan XP GPUs with 12 GB of memory.

If I change the config variable"tracker_specs.end_frame" to any frame before it gets stuck, it works just fine. Based on the symptoms, maybe there is some overflow or a memory issue, but I am not sure. Have you encountered this yourself?

**Comment by garylidd** [comment]
Hi, what is the last error, is the tracking process dead, or is the assert triggered?

**Comment by eriksandstroem** [comment]
> Hi, what is the last error, is the tracking process dead, or is the assert triggered?

The strange thing is that no error or assert is ever triggered, the code just gets stuck without any information. There are no asserts or errors that are triggered.

**Comment by garylidd** [comment]
We don't seem to have encountered such a problem. Do you have any other clues, or can you find out which step you are stuck in?

**Comment by eriksandstroem** [comment]
Thanks for your feedback! I will investigate if I can get it to run on another GPU. I have not yet investigated at what exact step it gets stuck, but will do so if I cannot get it to finish on the other GPU.

**Comment by eriksandstroem** [comment]
I have now tried some more things, but no success thus far. 

1. Ran multiple times on room 0. The code gets stuck between frame 1890-1900, but not at the same frame every time. I tried to debug the issue, but have not had any success thus far.
2. I tried running the code on another cluster, but without success. 
3. I tried running the code with fewer map and tracking iterations to speed up the debugging. I used only 1 iteration for mapping and tracking. On a 12 GB GPU, it says that I am running out of GPU memory after around 900 frames. Could this be the issue?

**Comment by eriksandstroem** [comment]
Some more debugging on the other cluster has revealed the following issue. Now, I cannot run until frame 1800-ish, but already at the first frame do I hit the following error, which happens at this line: 

https://github.com/zju3dv/Vox-Fusion/blob/main/src/tracking.py#L82

Specifically, the error happens when we load the rgb image onto the GPU in the RGBDFrame class: https://github.com/zju3dv/Vox-Fusion/blob/main/src/frame.py#L14




`******* initializing first_frame: 0
initializing the first frame ...
mapping process started!
******* tracking process started! *******
tracking frame:   0%|                                                                                                                                                               | 0/1999 [00:00<?, ?it/s][W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '`

**Comment by garylidd** [comment]
Hi, have you run through the Replica dataset? From the feedback, running on Replica is relatively stable.

**Comment by eriksandstroem** [comment]
Hi,
Yes I am only running on room 0 from the replica dataset now. 

I found one issue. It was that I was not requesting enough CPU RAM when submitting the jobs. With 50 GB it works on a 12 GB GPU.

Now, I am facing a very strange issue. I can run the code and get the mesh on a small amount of frames, but when I run it on the entire trajectory, I get an error. See below for the run on 20 frames, which is successful.

`******* initializing first_frame: 0
initializing the first frame ...
mapping process started!
insert keyframe
******* tracking process started! *******
tracking frame: 100%|█████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:21<00:00,  1.13s/it]
========== stop_mapping set ==========
******* tracking process died *******
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
********** post-processing 0 steps **********
******* extracting final mesh *******
/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1666643004612/work/aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
********** get color from network **********
tensor(924)
******* mapping process died *******
/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
`

Below is the run on 2000 frames, which fails when we are about to mesh.

`******* initializing first_frame: 0
initializing the first frame ...
mapping process started!
insert keyframe
******* tracking process started! *******
tracking frame:   3%|██                                                                                 | 51/1999 [00:57<45:34,  1.40s/it]insert keyframe
********** current num kfs: 2 **********
tracking frame:   5%|████▏                                                                             | 102/1999 [02:02<45:36,  1.44s/it]insert keyframe
********** current num kfs: 3 **********
tracking frame:   8%|██████▎                                                                           | 154/1999 [03:17<39:49,  1.29s/it]insert keyframe
********** current num kfs: 4 **********
tracking frame:  10%|████████▍                                                                         | 205/1999 [04:42<47:35,  1.59s/it]insert keyframe
********** current num kfs: 5 **********
tracking frame:  13%|██████████▌                                                                       | 256/1999 [06:16<50:34,  1.74s/it]insert keyframe
********** current num kfs: 6 **********
tracking frame:  15%|████████████▌                                                                     | 307/1999 [07:49<50:36,  1.79s/it]insert keyframe
********** current num kfs: 7 **********
tracking frame:  18%|██████████████▋                                                                   | 358/1999 [09:23<49:11,  1.80s/it]insert keyframe
********** current num kfs: 8 **********
tracking frame:  20%|████████████████▊                                                                 | 409/1999 [10:56<48:54,  1.85s/it]insert keyframe
********** current num kfs: 9 **********
tracking frame:  23%|██████████████████▊                                                               | 460/1999 [12:30<45:34,  1.78s/it]insert keyframe
********** current num kfs: 10 **********
tracking frame:  26%|████████████████████▉                                                             | 511/1999 [14:01<42:22,  1.71s/it]insert keyframe
********** current num kfs: 11 **********
tracking frame:  28%|███████████████████████                                                           | 562/1999 [15:31<43:08,  1.80s/it]insert keyframe
********** current num kfs: 12 **********
tracking frame:  31%|█████████████████████████▏                                                        | 613/1999 [17:01<41:42,  1.81s/it]insert keyframe
********** current num kfs: 13 **********
tracking frame:  33%|███████████████████████████▏                                                      | 664/1999 [18:37<43:31,  1.96s/it]insert keyframe
********** current num kfs: 14 **********
tracking frame:  36%|█████████████████████████████▎                                                    | 715/1999 [20:19<42:08,  1.97s/it]insert keyframe
********** current num kfs: 15 **********
tracking frame:  38%|███████████████████████████████▍                                                  | 766/1999 [22:06<43:22,  2.11s/it]insert keyframe
********** current num kfs: 16 **********
tracking frame:  41%|█████████████████████████████████▌                                                | 817/1999 [23:58<43:18,  2.20s/it]insert keyframe
********** current num kfs: 17 **********
tracking frame:  43%|███████████████████████████████████▌                                              | 868/1999 [25:51<41:05,  2.18s/it]insert keyframe
********** current num kfs: 18 **********
tracking frame:  46%|█████████████████████████████████████▋                                            | 919/1999 [27:41<39:11,  2.18s/it]insert keyframe
********** current num kfs: 19 **********
tracking frame:  49%|███████████████████████████████████████▊                                          | 970/1999 [29:34<37:43,  2.20s/it]insert keyframe
********** current num kfs: 20 **********
tracking frame:  51%|█████████████████████████████████████████▎                                       | 1021/1999 [31:28<36:33,  2.24s/it]insert keyframe
********** current num kfs: 21 **********
tracking frame:  54%|███████████████████████████████████████████▍                                     | 1072/1999 [33:24<36:35,  2.37s/it]insert keyframe
********** current num kfs: 22 **********
tracking frame:  56%|█████████████████████████████████████████████▌                                   | 1123/1999 [35:24<33:57,  2.33s/it]insert keyframe
********** current num kfs: 23 **********
tracking frame:  59%|███████████████████████████████████████████████▌                                 | 1174/1999 [37:26<32:07,  2.34s/it]insert keyframe
********** current num kfs: 24 **********
tracking frame:  61%|█████████████████████████████████████████████████▋                               | 1225/1999 [39:28<30:53,  2.39s/it]insert keyframe
********** current num kfs: 25 **********
tracking frame:  64%|███████████████████████████████████████████████████▋                             | 1276/1999 [41:26<28:20,  2.35s/it]insert keyframe
********** current num kfs: 26 **********
tracking frame:  66%|█████████████████████████████████████████████████████▊                           | 1327/1999 [43:22<25:13,  2.25s/it]insert keyframe
********** current num kfs: 27 **********
tracking frame:  69%|███████████████████████████████████████████████████████▊                         | 1378/1999 [45:17<23:33,  2.28s/it]insert keyframe
********** current num kfs: 28 **********
tracking frame:  71%|█████████████████████████████████████████████████████████▉                       | 1429/1999 [47:16<21:02,  2.21s/it]insert keyframe
********** current num kfs: 29 **********
tracking frame:  74%|███████████████████████████████████████████████████████████▉                     | 1480/1999 [49:16<19:50,  2.29s/it]insert keyframe
********** current num kfs: 30 **********
tracking frame:  77%|██████████████████████████████████████████████████████████████                   | 1531/1999 [51:20<18:34,  2.38s/it]insert keyframe
********** current num kfs: 31 **********
tracking frame:  79%|████████████████████████████████████████████████████████████████                 | 1582/1999 [53:18<16:35,  2.39s/it]insert keyframe
********** current num kfs: 32 **********
tracking frame:  82%|██████████████████████████████████████████████████████████████████▏              | 1633/1999 [55:20<14:40,  2.41s/it]insert keyframe
********** current num kfs: 33 **********
tracking frame:  84%|████████████████████████████████████████████████████████████████████▏            | 1684/1999 [57:20<11:51,  2.26s/it]insert keyframe
********** current num kfs: 34 **********
tracking frame:  87%|██████████████████████████████████████████████████████████████████████▎          | 1735/1999 [59:20<10:26,  2.37s/it]insert keyframe
********** current num kfs: 35 **********
tracking frame:  89%|██████████████████████████████████████████████████████████████████████▌        | 1786/1999 [1:01:18<07:33,  2.13s/it]insert keyframe
********** current num kfs: 36 **********
tracking frame:  92%|████████████████████████████████████████████████████████████████████████▌      | 1837/1999 [1:03:12<06:14,  2.31s/it]insert keyframe
********** current num kfs: 37 **********
tracking frame:  94%|██████████████████████████████████████████████████████████████████████████▌    | 1888/1999 [1:05:10<04:16,  2.31s/it]insert keyframe
********** current num kfs: 38 **********
tracking frame:  97%|████████████████████████████████████████████████████████████████████████████▋  | 1939/1999 [1:07:02<02:11,  2.19s/it]insert keyframe
********** current num kfs: 39 **********
tracking frame: 100%|██████████████████████████████████████████████████████████████████████████████▋| 1990/1999 [1:08:55<00:20,  2.25s/it]insert keyframe
********** current num kfs: 40 **********
tracking frame: 100%|███████████████████████████████████████████████████████████████████████████████| 1999/1999 [1:09:17<00:00,  2.08s/it]
========== stop_mapping set ==========
******* tracking process died *******
Process Process-2:
Traceback (most recent call last):
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch_net/nudel_second/esandstroem/opportunistic_3d_capture/Erik_3D_Reconstruction_Project/3rdparty/Vox-Fusion/src/mapping.py", line 86, in spin
    tracked_frame = kf_buffer.get()
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
`

To highlight the specific error, see below: 

`Traceback (most recent call last):
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch_net/nudel_second/esandstroem/opportunistic_3d_capture/Erik_3D_Reconstruction_Project/3rdparty/Vox-Fusion/src/mapping.py", line 86, in spin
    tracked_frame = kf_buffer.get()
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/scratch_net/nudel/esandstroem/venvs/voxfusion_env/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
`

I don't understand what the difference is between running on 20 vs 2000 frames when it comes to producing the mesh etc. Do you have any idea? Perhaps 50 GB is not enough. 

Edit: I was able to run with 70 GB CPU RAM and then it works! So we can close this issue. :)

**Comment by garylidd** [comment]
We didn't pay much attention to the CPU RAM usage, it seems that this is a place that needs further optimization. Thanks for the information.

**Comment by lixinhaiyk** [comment]
> 

hi,bro,I meet the same problem in room0,and how could you run it on 12GB,I test it on a100 and 4090,this sequence need 22G max GPU mem, and still I could not save the finally result when this bug occurs on CPU ram 128G GPU 24G.Thanks a lot.

**Comment by eriksandstroem** [comment]
I don't think my issue was related to gpu memory but rather cpu ram that is
available. Try to request more ram.

**Comment by garylidd** [comment]
Hi,

We found that the storage of intermediate results may lead to a sudden increase in GPU memory, and the storage of intermediate results can be turned off by setting mesh_freq to 0.
