### ISSUE TITLE
How is the voxel size during meshing computed?

### ISSUE THREAD

**Issue by eriksandstroem** [zju3dv/Vox-Fusion#25]
Hi,
I am trying to understand how the voxel size during meshing is computed. In the config, there is the mesh_res variable, but how does this relate to the voxel size? 

When looking at the code and running it on room 0, I find that the res variable here: https://github.com/zju3dv/Vox-Fusion/blob/12afdf07adf29e2dab021afacfcb94cf02c4f17e/src/utils/mesh_util.py#L148, gets set to around 0.142. Does that mean that the effective voxel size during meshing is 14.2 cm?

Additionally, I am curious, are the results in the paper the best out of X runs or the average of X runs or just a one time result? Edit: I ran the code on room 0 and my average ate rmse after alignment is 0.0137 m. There were no outliers among the runs. Perhaps the config files you provide are different from the ones you used for the paper?

Cheers!

**Comment by garylidd** [comment]
Hi, 
We do a separate surface extraction for each voxel, mesh_res is used to determine the number of samples for each dimension within the voxel, voxel_size is the actual size for each voxel.
We report the result of a single run. Our method should be relatively stable in the Replica dataset. We use the identical pose comparison method provided in Nice-SLAM. 
We attach the result of room0 for your reference.
[room0.zip](https://github.com/zju3dv/Vox-Fusion/files/10538066/room0.zip)

**Comment by eriksandstroem** [comment]
Thanks!
