### ISSUE TITLE
Using ground truth poses during reconstruction

### ISSUE THREAD

**Issue by eriksandstroem** [zju3dv/Vox-Fusion#29]
Hi,
What is the easiest way to run your code with ground truth poses? I see that there is the config option "use_gt", but that does not seem to influence whether gt poses are retrieved during mapping. I could try myself to hack it, but would like to check with you as well since you know the codebase.

Cheers,

**Comment by xingruiy** [comment]
Hi @tfy14esa ,

`use_gt` is a legacy option that is unused in our release code.
With regard to your question, I would say initializing frame poses from the ground truth ones, then keeping them constant by moving pose optimizers out of the optimization loop is the easiest option.

**Comment by eriksandstroem** [comment]
Thanks, makes sense.
