### ISSUE TITLE
About camera translation offset

### ISSUE THREAD

**Issue by gwangtaepark** [zju3dv/Vox-Fusion#3]
Hi, thank you for sharing the project.

It src/frame.py , a fixed translation offset (+10) value is always used.
Is there any reason you have such specific offset value?
Does it matter if I set this value as zero?

**Comment by garylidd** [comment]
Thank for pointing out. We have implemented a relatively simple morton encoding, which currently does not support negative coordinates. This offset ensures that voxel coordinates are positive in our experiments. You can change it based on potential scene size.

**Comment by gwangtaepark** [comment]
Ok, I see. Thanks for quick response
