### ISSUE TITLE
The initialization of svo (sparse octree). 

### ISSUE THREAD

**Issue by JunyuanDeng** [zju3dv/Vox-Fusion#30]
Thanks for sharing this job!

I notice that you set 256 as initialization in the 75 line of [`mapping.py`](https://github.com/zju3dv/Vox-Fusion/blob/main/src/mapping.py#:~:text=self.svo.init(256%2C%20embed_dim%2C%20self.voxel_size)). 

What does it mean? Can I set it to a huge number, like 256\*256\*256, as I want to run it for a big room? 

Best regards,

**Comment by xingruiy** [comment]
Hi @Rotatingpencil ,

Thanks for your interest in our work, the initialization parameter `256`, or `grid_dim` is chosen such that `grid_dim=2^n_octree_layer`. In this case  `n_octree_level=8`.
If you run into issues with larger areas, you could increase it by increasing the maximum octree levels. Theoretically, every additional layer would increase the size of the map by 2 on each axis.

**Comment by JunyuanDeng** [comment]
I got it! Thanks for your reply!
