### ISSUE TITLE
Replica room_0 ate value evaluation

### ISSUE THREAD

**Issue by jhch1995** [zju3dv/Vox-Fusion#33]
Hi, thank you for the excellent work. i use the default parameters in room_0.yaml to generate the tracker frame pose. To evaluate the accuracy of pose estimation about room_0, I rewrite an ate evaluation file referencing nice-slam. After running 2000 frames, I get the evaluation result which is the ate value is 0.0109m. It has some gaps in your papers (0.0027). It is confusing to me, it may have some mistakes operation in my evaluation process. Can you give more details about the ate evaluation?  Thank you very much!

**Comment by garylidd** [comment]
Hi,

We found a bug in the evaluation script we used, which affected the estimated pose accuracy in Tables 1 and 3 in the original paper. We have corrected this problem and re-run the results with updated configurations. Please refer to the updated arxiv version of our paper for the corrected results. We also have uploaded the full results on [OneDrive](https://zjueducn-my.sharepoint.com/:f:/g/personal/garyli_zju_edu_cn/EgEhBqp29R1Gl6kREj88nQ4BAzS_ezOFtiub6ZsvywO4og?e=QoRpr5) and updated the configuration files accordingly. You can use the new configuration files in the "configs" directory to run the results for Repica dataset and ScanNet dataset.
