### ISSUE TITLE
how to visualize the tracking and mapping process

### ISSUE THREAD

**Issue by Marquess98** [zju3dv/Vox-Fusion#36]
I run the view.py in demo file with configs/replica/room_0.yaml and logs/replica/room0/scene1/bak/config.yaml, but I can't see any results except for a white open3d windows.
could you give me any advise to solve this problems? Thanks!

**Comment by laliwang** [comment]
I have the same question. With results of misc/scene_data_**.pkl in the right path, I only get a white window too.

**Comment by ignotuspeverel** [comment]
I came across the same problem

**Comment by xingruiy** [comment]
We didn't release any code relating to live visualization, the viewer window is only a placeholder. Our results are generated with intermediate checkpoint files from the log folder.

**Comment by Aurora-chevalier** [comment]
> 我们没有发布任何与实时可视化相关的代码，查看器窗口只是一个占位符。我们的结果是由日志文件夹中的中间检查点文件生成的。



> We didn't release any code relating to live visualization, the viewer window is only a placeholder. Our results are generated with intermediate checkpoint files from the log folder.

Hello, can you tell me exactly how to generate the intermediate check file from the log folder？thanks
