### ISSUE TITLE
why I can't build the while,it always come out the error

### ISSUE THREAD

**Issue by emiald** [zju3dv/Vox-Fusion#39]
creating C:\nerf\Vox-Fusion-main\third_party\sparse_octree\build\lib.win-amd64-cpython-38
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\15355\anaconda3\envs\plenoxel\lib\site-packages\torch\lib /LIBPATH:C:\Users\15355\anaconda3\envs\plenoxel\libs /LIBPATH:C:\Users\15355\anaconda3\envs\plenoxel /LIBPATH:C:\Users\15355\anaconda3\envs\plenoxel\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x86" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit_svo build\temp.win-amd64-cpython-38\Release\src\bindings.obj build\temp.win-amd64-cpython-38\Release\src\octree.obj /OUT:build\lib.win-amd64-cpython-38\svo.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-38\Release\src\svo.cp38-win_amd64.lib
LINK : error LNK2001: 无法解析的外部符号 PyInit_svo
build\temp.win-amd64-cpython-38\Release\src\svo.cp38-win_amd64.lib : fatal error LNK1120: 1 个无法解析的外部命令
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120

**Comment by xingruiy** [comment]
building udner windows is not tested. Please check if your have all the required packages installed.
