### ISSUE TITLE
您好OneDrive的链接过期了，可以更新一下吗？

### ISSUE THREAD

**Issue by SharineLee** [zju3dv/Vox-Fusion#42]

**Comment by abdulkarimatrash** [comment]
@SharineLee thank you for pointing that out.
I just noticed the same problem.
The OneDrive link is not working at the moment. 
We hope one of the authors can update it.

Thank you in advance for your time and effort.

**Comment by SharineLee** [comment]
> @SharineLee thank you for pointing that out.
> I just noticed the same problem.
> The OneDrive link is not working at the moment. 
> We hope one of the authors can update it.
> 
> Thank you in advance for your time and effort.

I cannot open this OneDrive link. It seems that I don't have the permission.

![IMG_20230608_222607.jpg](https://github.com/zju3dv/Vox-Fusion/assets/26604823/0aa10ce6-14fb-4a7e-ba94-fe03eb069045)

**Comment by garylidd** [comment]
Hi, I have updated the onedrive link.

**Comment by abdulkarimatrash** [comment]
@garylidd 
Thank you for your fast reply. 

Sadly, as @SharineLee mentioned, the problem is still valid. It seems like our emails have to be on your list for us to be able to download the materials. Perhaps you have to make them publically available. 

Thank you for your patience and time !

**Comment by abdulkarimatrash** [comment]
@garylidd excuse me for bothering you, but are there any updates?

**Comment by bobfacer** [comment]
@garylidd It seems that we don't have the permission to the content of your onedrive

**Comment by garylidd** [comment]
Sorry I didn't notice the permission issue, I re-updated the link, please check.

**Comment by abdulkarimatrash** [comment]
@garylidd  thank you, it is open now for everyone :)

**Comment by xingruiy** [comment]
hi all,
we've replace onedrive with the more stable google drive. hopefully should solve all the link expiring issue.
