### ISSUE TITLE
The net setup is not same as the article described

### ISSUE THREAD

**Issue by JunyuanDeng** [zju3dv/Vox-Fusion#5]
I notice that in the file "replica.yaml", you set depth: 2 and width: 128. I checked in `src/variation/nrgbd.py`, these means the 2 FC layers for sdf and 128 hidden units. But in your article, there are 4 FC and 258 hidden units. Why there are differences between real implementation and article description?  

Thanks for your reply!

**Comment by garylidd** [comment]
Thanks for pointing it out. 

We did some experiments with fewer network parameters recently and found similar results. However, you can revert to the same parameters as the article.

**Comment by JunyuanDeng** [comment]
Thanks for your reply, now I understand!
