### ISSUE TITLE
When I run the code I get a warning about sharing CUDA tensor.

### ISSUE THREAD

**Issue by zhw-github** [zju3dv/Vox-Fusion#6]
There is a warning when I run the code, but it does not affect the normal operation of the program.
I execute the code using the following command. python  demo/run.py configs/replica/room_0.yaml.
operation result：
******* initializing first_frame: 0
initializing the first frame ...
mapping process started!
insert keyframe
******* tracking process started! *******
tracking frame:  52%|████████████████████                   | 51/99 [00:51<01:02,  1.29s/it]insert keyframe
********** current num kfs: 2 **********
tracking frame: 100%|███████████████████████████████████████| 99/99 [01:41<00:00,  1.02s/it]
========== stop_mapping set ==========
******* tracking process died *******
********** post-processing 0 steps **********
******* extracting final mesh *******
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
********** get color from network **********
tensor(1457)
******* mapping process died *******
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
I wonder if the warning can be eliminated and if it has something to do with having multiple GPUs on my computer

**Comment by garylidd** [comment]
Thanks for pointing out, we will fix it later. 

The critical problem with multiple GPUs is that they cannot efficiently access shared GPU memory.  We are working on this as well.
