### ISSUE TITLE
When I Run Demo,  I got esource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown and Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

### ISSUE THREAD

**Issue by zerolfq** [zju3dv/Vox-Fusion#7]
========== stop_mapping set ==========
******* tracking process died *******
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
********** post-processing 0 steps **********
******* extracting final mesh *******
/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
********** get color from network **********
/home/xyz/Github/Vox-Fusion/src/utils/mesh_util.py:110: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  voxel_pos = points // self.voxel_size
tensor(1459)
******* mapping process died *******
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
/home/xyz/anaconda3/envs/vox/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by garylidd** [comment]
Thanks for pointing out, we will fix it later.

**Comment by dongshengLiu** [comment]
same question.
