### ISSUE TITLE
Questions on keyframe selection

### ISSUE THREAD

**Issue by gwangtaepark** [zju3dv/Vox-Fusion#8]
Hello, I have a question on keyframe selection method in your paper.
It your paper, keyframe is determined by ray intersection test. 
In this case, should ray be a dense 2D rays or sampled rays?
I think that there's no need to test all rays inside camera view, but it may require more rays than the tracking process.  

Thanks for sharing the cool work.

**Comment by garylidd** [comment]
Hi, it is actually a "voxel" intersection test, not "ray". It computes the overlap between incoming voxels and existing voxels.

However, we haven't included this feature in this clean version yet. We will update it later.
